"""Add Ranking model

Revision ID: 531cf84f0268
Revises: c9a5c96e31ed
Create Date: 2024-12-02 19:10:00.883168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531cf84f0268'
down_revision = 'c9a5c96e31ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('category_en', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               nullable=False)
        batch_op.drop_column('title')
        batch_op.drop_column('link')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('link', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('position',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('url')
        batch_op.drop_column('source')
        batch_op.drop_column('category_en')
        batch_op.drop_column('category')
        batch_op.drop_column('year')

    # ### end Alembic commands ###
