"""empty message

Revision ID: c9a5c96e31ed
Revises: 5b1d8bdb5b4c
Create Date: 2024-12-02 18:27:03.566639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a5c96e31ed'
down_revision = '5b1d8bdb5b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('category')
        batch_op.drop_column('year')
        batch_op.drop_column('source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('year', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=200), nullable=False))
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('title')

    # ### end Alembic commands ###
